# --- Core Colors ---
#foreground   #cbd1d6
#background   #150304
#cursor       #cbd1d6
foreground #9bb1c4
background #060a0f
cursor     #53a3b0
# --- ANSI Colors ---

# Black
color0  #1B1F3F
color8  #3F291B

# Red
color1  #628DB3
color9  #628DB3

# Green
color2  #718fcc
color10 #718fcc

# Yellow
color3  #6b9fd5
color11 #6b9fd5

# Blue
color4  #82aaff
color12 #82aaff

# Magenta
color5  #95add9
color13 #95add9

# Cyan
color6  #accee8
color14 #accee8

# White
color7  #e4e5e8
color15 #e4e5e8
